#!/usr/bin/env python3
"""Bakes src/font8x8.h: 9x9, 8bpp alpha-coverage glyphs (DejaVu Sans Mono
Bold), same method the file's own header comment describes (size from
font ascent+descent metrics so every glyph shares one baseline, 8x
supersample downsampled to 9x9 via Lanczos, per-glyph horizontal centering
only). This is the *fallback* glyph table -- every scale force_shadow.c
actually draws at (1.0/1.5/2.0/2.5/3.0) is served by the hinted font_hi.h
table instead (see tools/gen_font_hi.py); font8x8 only matters if a draw
call ever uses an unbaked scale, and as the source render_preview.c /
render_conf_preview.c upscale for host-side layout checks.

  docker run --rm -v "$PWD":/w -v /usr/share/fonts/truetype/dejavu:/fonts:ro \
    -w /w python:3.11-slim bash -c "pip install -q pillow && python3 tools/gen_font8x8.py"
"""
from PIL import Image, ImageDraw, ImageFont

# Keep in sync with tools/gen_font_hi.py's CHARS -- font_glyph_index() in
# force_shadow.c indexes both tables by the same position in this string.
CHARS = (" ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
         "0123456789.-/_>%+:#")
FONT = "/fonts/DejaVuSansMono-Bold.ttf"
CELL = 9
SUPER = 8  # supersample factor before Lanczos downsample to CELL x CELL

size = CELL * SUPER
font = ImageFont.truetype(FONT, int(size * 0.78))
ascent, descent = font.getmetrics()
total = ascent + descent
scale = (size * 0.86) / total  # leave a real top/bottom margin, no clipping
font = ImageFont.truetype(FONT, int(size * 0.78 * scale))
ascent, descent = font.getmetrics()
baseline = (size - (ascent + descent)) // 2 + ascent

lines = ["/* GENERATED by tools/gen_font8x8.py -- do not edit. */\n"]
lines.append(f"static const uint8_t font8x8[][{CELL*CELL}] = {{\n")
for c in CHARS:
    big = Image.new("L", (size, size), 0)
    if c != " ":
        d = ImageDraw.Draw(big)
        adv = font.getlength(c)
        d.text(((size - adv) / 2, baseline), c, font=font, anchor="ls", fill=255)
    small = big.resize((CELL, CELL), Image.LANCZOS)
    vals = list(small.tobytes())
    name = "SPACE" if c == " " else c
    lines.append("    {" + ", ".join(str(v) for v in vals) + f"}}, /* '{name}' */\n")
lines.append("};\n\n")
lines.append(f'static const char font_chars[] = "{CHARS}";\n')
open("src/font8x8.h", "w").write("".join(lines))
print(f"ok: {len(CHARS)} glyphs")
