#!/usr/bin/env python3
"""Bakes src/font_hi.h: hinted, natively-sized glyph bitmaps (DejaVu Sans Mono
Bold) for the text scales the renderer uses (1.5x, 2x, 2.5x of the 9px cell),
so text is drawn 1:1 instead of nearest-neighbour-upscaling a 9x9 bitmap.
Each glyph sits in an advance cell of (int)(10*scale) x (int)(9*scale+.5)
px -- the same cell the old scaled font used, so layouts don't move.

  docker run --rm -v "$PWD":/w -v /usr/share/fonts/truetype/dejavu:/fonts:ro \
    -w /w python:3.11-slim bash -c "pip install -q pillow && python3 tools/gen_font_hi.py"
"""
from PIL import Image, ImageDraw, ImageFont

CHARS = " ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.-/>%+:"   # == font_chars in font8x8.h
SCALES = [1.5, 2.0, 2.5]
FONT = "/fonts/DejaVuSansMono-Bold.ttf"
CAP = 0.729  # DejaVu cap height / em

out = ["/* GENERATED by tools/gen_font_hi.py -- do not edit. */\n"]
for s in SCALES:
    cw, ch = int(10 * s), int(9 * s + 0.5)
    size = ch
    font = ImageFont.truetype(FONT, size)
    cap = round(CAP * size)
    base = (ch + cap) // 2
    name = str(s).replace(".", "_")
    out.append(f"#define FONT_HI_{name}_W {cw}\n#define FONT_HI_{name}_H {ch}\n")
    out.append(f"static const uint8_t font_hi_{name}[][{cw * ch}] = {{\n")
    for c in CHARS:
        im = Image.new("L", (cw, ch), 0)
        if c != " ":
            d = ImageDraw.Draw(im)
            adv = font.getlength(c)
            d.text(((cw - 1 - adv) / 2, base), c, font=font, fill=255, anchor="ls")
        out.append("    {" + ",".join(str(v) for v in im.tobytes()) + "},\n")
    out.append("};\n")
open("src/font_hi.h", "w").write("".join(out))
print("ok")
